[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
whisper = "AD1BetBSjTDkpQBbzKYaswz9KrHraz54P1Vt2AGNJw5Z"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
