[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
whisper = "6ac2jbi5FMSj9NQRxzWPgWjbd6WJR7CiaPXxeTW2SW7H"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
